### ISSUE TITLE
Go sciter

### ISSUE THREAD

**Issue by whisperecean** [Dadido3/D3pixelbot#12]
Hi. I did not find a way how to contact you that's why I am opening an issue here hoping you get a notification.

I'd like to use Go+Sciter to develop some simple menubar application. Did you stop using Go and Sciter do you think your fork still works or did you merge the changes that prevent the program from crashing when using goroutines? 

Many thanks!

**Comment by Dadido3** [comment]
Hi,

i haven't used Sciter in a while and my fork of go-sciter may be a bit stale, so i can't tell how well it works with the newest version of Sciter. It's probably better to use the official repository.

The bug that caused crashes due to Sciter not being pinned to the main thread got [fixed in 2021](https://github.com/sciter-sdk/go-sciter/pull/282). And some other fixes of mine were also pulled into the main repo.

So, as long as you don't need the [additional getter and setter methods for time values](https://github.com/Dadido3/go-sciter/blob/1c12b47f58a45e29b9ffaf6d0265ffde14493419/sciter.go#L2067-L2083) which i added, my fork of go-sciter doesn't offer anything else right now.

**Comment by whisperecean** [comment]
Hello thanks! I have not made the systray lib working with sciter but that is not required anymore as sciter supports systray natively. Not sure it would even be possible based on what @pravic said https://github.com/sciter-sdk/go-sciter/issues/135

I am curious how should I do some backend processing using goroutines when creating a window blocks a thread. I have not figured that one out yet :/...Any idea?

**Comment by Dadido3** [comment]
You can spawn goroutines, but you should not create windows in goroutines. A few points that may help:

- Create your windows only from the main thread. (Callback functions passed via `w.DefineFunction` will also be run in the main thread)
- Define [callbacks that you can call from within Sciter](https://github.com/Dadido3/D3pixelbot/blob/580f6a3da24ad39bf15c12882825364ca5dfe24f/scitercanvas.go#L63C2-L63C18) to process stuff in go. You can then either directly return values to Sciter, or you can open up a goroutine and [pass data to Sciter asynchronously via another callback](https://github.com/Dadido3/D3pixelbot/blob/580f6a3da24ad39bf15c12882825364ca5dfe24f/scitercanvas.go#L119C5-L119C20).

**Comment by Dadido3** [comment]
I'll close this issue, as it has nothing to do with the bot.
